# Generated by Django 3.1.13 on 2021-10-14 09:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWonderfulPage',
            fields=[
                ('newspage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.newspage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'news.newspage'),
        ),
    ]
